name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Create directories and set permissions
        run: |
          mkdir dist          
          mkdir target          
          mkdir node_modules
          sudo chown -R 1000:1000 .

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          skipContainerUserIdUpdate: true
          imageName: ghcr.io/ssoudan/web-nuts-rs-devcontainer
          cacheFrom: ghcr.io/ssoudan/web-nuts-rs-devcontainer:latest
          push: never
          runCmd: |
            id
            ls -lah
            cargo test --all-targets --all-features
            cargo clippy --all-targets --all-features -- -D warnings            
            cargo build
            npm install
            npm run release

      - name: Restore permissions
        run: |
          sudo chown -R $USER .

      - name: Copy files to _site
        run: |
          mkdir -p _site
          cp -r dist/* _site/
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done